server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/bunnuoc-demo}
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

  cache:
    type: redis
  redis:
    url: ${REDIS_URL:redis://localhost:6379}

  rabbitmq:
    addresses: ${RABBIT_MQ_URL:amqp://guest:guest@localhost:5672}

app:
  time:
    expiryTime: 3600

key:
  jwt:
    value: ${KEY_JWT:12345678901234567890123456789012}